micronaut:
  server:
    ssl:
      enabled: true
      key-store:
        path: classpath:server.p12
        password: password
        type: PKCS12
    netty:
      listeners:
        http1:
          port: 8080
          ssl: false
        https:
          port: 8443
          ssl: true